# Generated by Django 4.1.5 on 2023-05-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('rent', 'rent'), ('sell', 'sell')], default='rent', max_length=6)),
                ('photo', models.ImageField(upload_to='static/pro-img')),
            ],
        ),
    ]
