# Generated by Django 4.1.5 on 2023-05-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.ImageField(upload_to='pro-img/'),
        ),
    ]
