# Generated by Django 4.1.5 on 2023-05-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_property_price_alter_property_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='purpose',
            new_name='prop_type',
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='desc',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
