# Generated by Django 4.2 on 2023-05-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_agents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
    ]
